-- ============================================================================
-- Snowflake Demo Cleanup
-- ============================================================================
-- Drops all objects generated by the demo pipelines and truncates raw data
-- tables. Leaves Terraform-managed schemas, warehouses, and table DEFINITIONS
-- intact — only their CONTENTS and DERIVED objects are removed.
--
-- After running this:
--   • Re-populate raw data:   python ingest/fetch_stock_prices.py
--                             python ingest/fetch_sec_filings.py
--   • Re-build pipelines:     snowsql -c myaccount -f sql/ml_pipeline.sql
--                             snowsql -c myaccount -f sql/cortex_pipeline.sql
--
-- NOTE: Snowsight Workspace SQL files (worksheets created by run_demo.js)
-- live in user workspace state, not as schema objects. They must be deleted
-- manually from the Snowsight UI under Projects → Workspaces.
-- ============================================================================

USE DATABASE AI_CORTEX_DEMO;

-- ── ML_MODELS schema: drop pipeline-created objects ────────────────────────
USE SCHEMA ML_MODELS;

DROP TASK     IF EXISTS REFRESH_STOCK_PREDICTIONS;
DROP VIEW     IF EXISTS MODEL_PERFORMANCE;
DROP TABLE    IF EXISTS STOCK_PREDICTIONS;
DROP MODEL    IF EXISTS STOCK_PRICE_MODEL;
DROP VIEW     IF EXISTS STOCK_FEATURES;

-- ── CORTEX_AI schema: drop pipeline-created objects ────────────────────────
USE SCHEMA CORTEX_AI;

DROP TASK     IF EXISTS PROCESS_NEW_FILINGS;
DROP VIEW     IF EXISTS EXECUTIVE_BRIEFING;
DROP VIEW     IF EXISTS MA_ACTIVITY;
DROP VIEW     IF EXISTS CLASSIFICATION_SUMMARY;
DROP VIEW     IF EXISTS SENTIMENT_TRENDS;
DROP VIEW     IF EXISTS FILING_ENTITIES;
DROP TABLE    IF EXISTS FILING_SUMMARIES;

-- ── DASHBOARDS schema: drop pipeline-created views ─────────────────────────
USE SCHEMA DASHBOARDS;

DROP VIEW     IF EXISTS SENTIMENT_HEATMAP;
DROP VIEW     IF EXISTS CORTEX_SUMMARY_STATS;
DROP VIEW     IF EXISTS CORTEX_AI_DASHBOARD;
DROP VIEW     IF EXISTS ML_SUMMARY_STATS;
DROP VIEW     IF EXISTS STOCK_PREDICTION_DASHBOARD;

-- ── Notebooks (any in demo schemas) ────────────────────────────────────────
-- Snowflake NOTEBOOK objects live per-schema. If any were created manually
-- in Snowsight, drop them here. Add lines as needed:
--   DROP NOTEBOOK IF EXISTS ML_MODELS.MY_NOTEBOOK;
--   DROP NOTEBOOK IF EXISTS CORTEX_AI.MY_NOTEBOOK;

-- ── RAW_DATA schema: truncate ingested data (preserve Terraform table defs) ─
USE SCHEMA RAW_DATA;

TRUNCATE TABLE IF EXISTS STOCK_PRICES;
TRUNCATE TABLE IF EXISTS SEC_FILINGS;
TRUNCATE TABLE IF EXISTS REAL_ESTATE;

-- ── Summary ────────────────────────────────────────────────────────────────
SELECT 'Cleanup complete. Re-run ingest + pipelines to rebuild.' AS STATUS;
